config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: :json} do
    resources :albums, only: [:index, :create, :show, :destroy]
    resources :photos, only: [:index, :create, :show]
  end
  resource :session, only: [:create, :destroy, :new]
  resources :users, only: [:create, :new]
  root to: "static_pages#root"
end

app/models/album.rb
class Album < ActiveRecord::Base

  has_many :photos,
  primary_key: :id,
  foreign_key: :album_id,
  class_name: "Photo"

  def self.current_user_albums(id)
    self.where("user_id = ?", id)
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  belongs_to :album,
  primary_key: :id,
  foreign_key: :album_id,
  class_name: "Album"
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :session_token, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/api/albums_controller.rb
class Api::AlbumsController < ApplicationController
  def index
    @albums = Album.current_user_albums(current_user.id).reverse
    render :index
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def create
    @album = Album.new(album_params)
    @album.user_id = current_user.id
    if @album.save!
      @albums = Album.all
      render :index
    end
  end

  private

  def album_params
    params.require(:album).permit(:tag, :start, :finish)
  end

end

app/controllers/api/photos_controller.rb
class Api::PhotosController < ApplicationController

  def create
    @photo = Photo.new(photo_params)
    if @photo.save!
      render :show
    end
  end

  def show
    @photo = Photo.find(params[:id])
    render :show
  end

  private

  def photo_params
    params.require(:photo).permit(:album_id, :creator, :vid_or_pic, :native_link, :photo_url, :thumbnail, :tag_time)
  end

end

app/controllers/application_controller.rb
require "byebug"

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :logged_in?
  helper_method :require_user!

  private

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !current_user.nil?
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_user!
    redirect_to new_user_url if current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.nil?
      flash.now[:errors] = ["Incorrect username and/or password"]
      render :new
    else
      login_user!(user)
      redirect_to root_url
    end
  end

  def destroy
    logout_user!
    render json: {}
  end

  def new
    render :new
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :require_user!
  
  def root
    render :root
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    if @user.save
      login_user!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end

  def show
    @user = current_user
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlbumMaker</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link href='https://fonts.googleapis.com/css?family=Quicksand:400,300,700' rel='stylesheet' type='text/css'>
  <!-- <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> -->
  <%= csrf_meta_tags %>
  <script type="text/javascript" charset="utf-8">
    window.current_username = '<%= current_user.username if current_user %>'
    window.current_userid = '<%= current_user.id if current_user %>'
    window.INSTAGRAM_API_KEY = "<%=ENV['INSTAGRAM_API_KEY']%>"
  </script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

app/views/static_pages/root.html.erb
<div id="content">
</div>
<%= javascript_include_tag 'application' %>

app/views/users/new.html.erb
<div class="logins_container">
  <h1 class="logins_header">Welcome to AlbumMaker</h1>

  <div class="logins">
    <%= render "shared/errors" %>
    <div class="logins_border">
    <form action="<%= users_url %>" method="post" class="logins">
      <input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

      <input type="text"
             placeholder=" username"
             name="user[username]"
             id="user_username"
             value="<%= @user.username %>">
      <br>

      <input type="password"
             placeholder=" password"
             name="user[password]"
             id="user_password"
             value="<%= @user.password %>">
      <br>
      <button class="login_submit_button">Sign Up</button>

    </form>
    <div class="login_or">Or</div>
    <form action="<%= session_url %>" method="post">
      <input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

      <input type="hidden" placeholder="username" name="user[username]" value="Guest" id="user_username">

      <input type="hidden" placeholder="password" name="user[password]" value="qwerty" id="user_password">

      <button class="guest_button">Sign in as Guest</button>
    </form>
  </div>
  </div>
  <div class="logins_switch">
    <%= link_to "Already signed up?", new_session_url %>
  </div>
</div>